### ISSUE TITLE
Why is cacl_time_diff so weird?

### ISSUE THREAD

**Issue by kunaltyagi** [WHILL/ros_whill#3]
The time [difference function](https://github.com/WHILL/ros_whill/blob/kinetic-devel/src/whill_modelc_publisher.cpp#L115) is not straight forward to understand. Can you help me in understanding it better?

**Comment by seiya0412** [comment]
Thanks for the comment.
That function calculates interval [in millisecond] between the latest and the second latest packets.
The data packet coming from WHILL CR itself contains an one-byte "timestamp [in millisecond]" which is a circular counter with max value of 201. 

Note: Why "201"? It is an implementation error in its firmware and will be fixed in the next release. (Both firmware and this ros_whill package.)

**Comment by kunaltyagi** [comment]
The values I've been observing have been more than 201 frequently, resulting in large positive `time_diff_ms` (because negative signed difference becomes large unsigned value)

**Comment by seiya0412** [comment]
That behavior is actually unexpected.
We are going to inspect CR's firmware to dig into the issue.
Thank you very much for letting us know.
